# Uncomment the next line to define a global platform for your project
  platform :ios, '13.0'

target 'CapCut' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'CHTCollectionViewWaterfallLayout'
  pod 'SQLite.swift'

  # Pods for CapCut

  target 'CapCutTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CapCutUITests' do
    # Pods for testing
  end

end
